// <auto-generated />
using System;
using EFCore.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCore.Dal.Migrations
{
    [DbContext(typeof(PgDbContext))]
    [Migration("20200109013424_CreateUsers")]
    partial class CreateUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EFCore.Dal.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CardNo")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(48)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Secret")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce32bd49-7a7c-4bd1-b2b9-7e960ad86306"),
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 125, 145, 246, 8, 55, 30, 8, 39, 107, 210, 68, 1, 116, 230, 57, 86, 2, 120, 234, 177, 121, 44, 76, 190, 197, 109, 134, 169, 38, 64, 111, 108, 143, 205, 168, 233, 183, 46, 50, 122, 81, 56, 179, 72, 126, 1, 163, 57, 192, 156, 207, 60, 150, 58, 219, 56, 220, 33, 65, 151, 192, 218, 216, 80, 169, 36, 149, 69, 245, 247, 116, 55, 82, 108, 98, 205, 61, 21, 183 },
                            Name = "JB",
                            Password = "$1$hZl6qs2E$ItJcuMjEHmlOZzHsy8OLF0",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 191, 142, 105, 186, 9, 175, 67, 186, 96, 210, 59, 1, 177, 49, 120, 46, 10, 114, 91, 35, 103, 69, 191, 15, 253, 132, 66, 140, 57, 91, 164, 89, 21, 248, 45, 206, 1, 31, 20, 0, 231, 186, 153, 108, 49, 166, 160, 6, 18, 99, 145, 230, 155, 43, 95, 64, 54, 63, 27, 162, 143, 232, 194, 235, 156, 160, 73, 169, 77, 93 }
                        },
                        new
                        {
                            Id = new Guid("3e177c71-f84e-4c23-9bf4-b322b350c8b2"),
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 68, 207, 60, 186, 33, 211, 230, 28, 122, 210, 68, 1, 136, 155, 86, 99, 55, 12, 11, 188, 221, 57, 171, 137, 74, 102, 116, 44, 163, 220, 242, 112, 2, 73, 108, 141, 243, 130, 116, 208, 139, 148, 11, 197, 145, 18, 209, 66, 132, 220, 82, 176, 0, 48, 207, 191, 32, 40, 99, 6, 218, 250, 73, 24, 105, 177, 20, 58, 105, 113, 219, 78, 69, 217, 38, 248, 110, 194, 245 },
                            Name = "Amy",
                            Password = "$1$ApKxMhQv$au86wf6A4nfPG9.uEXDtL1",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 194, 132, 202, 173, 174, 59, 132, 44, 118, 210, 59, 1, 44, 138, 97, 216, 69, 241, 62, 217, 171, 105, 4, 249, 129, 155, 162, 65, 158, 198, 235, 1, 111, 75, 44, 126, 176, 73, 231, 216, 123, 51, 181, 146, 164, 81, 195, 77, 181, 245, 80, 167, 230, 74, 215, 32, 210, 87, 97, 134, 159, 12, 68, 6, 225, 225, 179, 138, 67, 42 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
