// <auto-generated />
using System;
using EFCore.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCore.Dal.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200107104214_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EFCore.Dal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CardNo")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(48)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 101, 47, 228, 203, 185, 31, 159, 46, 111, 210, 68, 1, 90, 145, 234, 65, 103, 209, 226, 91, 95, 40, 157, 193, 72, 84, 181, 88, 133, 111, 60, 76, 204, 120, 24, 42, 12, 227, 101, 220, 97, 186, 242, 136, 170, 107, 8, 96, 63, 115, 46, 217, 61, 242, 99, 4, 23, 30, 206, 139, 92, 2, 129, 163, 109, 80, 17, 143, 158, 75, 205, 8, 13, 136, 76, 17, 41, 106, 151 },
                            Name = "JB",
                            Password = "$1$cF/yk48v$ibVzA2GlpG/BhkDdiXidf0",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 74, 125, 58, 148, 68, 84, 190, 193, 104, 210, 59, 1, 101, 51, 213, 173, 172, 148, 37, 189, 160, 228, 159, 119, 46, 77, 137, 76, 42, 150, 57, 176, 8, 82, 72, 76, 143, 95, 154, 31, 85, 183, 252, 230, 115, 166, 110, 151, 25, 232, 189, 81, 211, 112, 108, 43, 215, 16, 160, 199, 222, 196, 91, 17, 158, 48, 222, 137, 142, 158 }
                        },
                        new
                        {
                            Id = 2,
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 45, 229, 15, 197, 131, 150, 223, 179, 101, 210, 68, 1, 32, 133, 114, 214, 200, 144, 228, 145, 253, 117, 171, 217, 183, 211, 18, 20, 44, 37, 156, 2, 86, 87, 128, 69, 191, 9, 171, 121, 65, 99, 119, 124, 132, 250, 145, 68, 151, 67, 93, 125, 144, 79, 203, 246, 154, 102, 32, 42, 119, 214, 237, 121, 70, 151, 22, 74, 173, 48, 226, 236, 34, 224, 194, 53, 24, 197, 5 },
                            Name = "Amy",
                            Password = "$1$.Mkb5CxC$iFWhBx09ZddRatdC.My3d/",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 165, 83, 27, 255, 31, 98, 181, 39, 120, 210, 59, 1, 226, 19, 170, 86, 84, 163, 214, 253, 16, 9, 168, 107, 39, 20, 73, 207, 40, 163, 2, 14, 124, 24, 133, 57, 15, 218, 21, 232, 182, 83, 7, 41, 42, 136, 145, 223, 252, 21, 208, 49, 153, 223, 111, 196, 47, 254, 245, 255, 83, 244, 54, 239, 157, 159, 21, 140, 188, 242 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
