// <auto-generated />
using System;
using EFCore.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCore.Dal.Migrations
{
    [DbContext(typeof(PgDbContext))]
    [Migration("20210201085701_CreateMetadata")]
    partial class CreateMetadata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EFCore.Dal.Models.SysMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreateOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RemoveBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RemoveOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SysMetadatas", "system");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce32bd49-7a7c-4bd1-b2b9-7e960ad86307"),
                            CreateBy = "System",
                            CreateOn = new DateTimeOffset(new DateTime(2021, 2, 1, 8, 56, 59, 734, DateTimeKind.Unspecified).AddTicks(6872), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDisabled = false
                        },
                        new
                        {
                            Id = new Guid("3e177c71-f84e-4c23-9bf4-b322b350c8b3"),
                            CreateBy = "System",
                            CreateOn = new DateTimeOffset(new DateTime(2021, 2, 1, 8, 56, 59, 736, DateTimeKind.Unspecified).AddTicks(8593), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDisabled = false
                        });
                });

            modelBuilder.Entity("EFCore.Dal.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CardNo")
                        .HasColumnType("bytea");

                    b.Property<Guid?>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(48)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Secret")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("MetadataId");

                    b.ToTable("Users", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce32bd49-7a7c-4bd1-b2b9-7e960ad86306"),
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 95, 205, 153, 239, 78, 243, 64, 190, 125, 210, 68, 1, 220, 136, 209, 82, 136, 219, 77, 141, 15, 158, 168, 225, 50, 216, 252, 44, 205, 218, 136, 57, 160, 221, 244, 195, 238, 11, 139, 58, 115, 223, 230, 11, 86, 120, 149, 199, 107, 62, 142, 71, 149, 10, 144, 244, 92, 177, 96, 19, 200, 143, 174, 12, 240, 148, 89, 188, 130, 181, 51, 38, 113, 148, 83, 95, 110, 212, 253 },
                            MetadataId = new Guid("ce32bd49-7a7c-4bd1-b2b9-7e960ad86307"),
                            Name = "JB",
                            Password = "$1$zJP/PnDk$Z0KOO8xvM147Yr6cIix040",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 144, 211, 9, 216, 116, 116, 182, 180, 106, 210, 59, 1, 17, 195, 45, 14, 89, 71, 61, 112, 222, 39, 8, 45, 23, 81, 19, 118, 116, 129, 226, 204, 34, 215, 45, 40, 237, 180, 50, 193, 248, 129, 3, 124, 254, 81, 253, 132, 38, 251, 68, 38, 95, 39, 91, 20, 209, 150, 9, 204, 225, 129, 181, 120, 58, 210, 205, 223, 39, 49 }
                        },
                        new
                        {
                            Id = new Guid("3e177c71-f84e-4c23-9bf4-b322b350c8b2"),
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 192, 19, 165, 98, 75, 27, 212, 127, 121, 210, 68, 1, 120, 66, 104, 134, 204, 61, 191, 103, 158, 209, 98, 50, 184, 139, 199, 11, 174, 53, 225, 147, 26, 178, 117, 239, 92, 156, 8, 138, 6, 161, 59, 163, 23, 13, 153, 88, 164, 101, 78, 213, 189, 5, 161, 115, 38, 228, 60, 35, 177, 119, 146, 77, 171, 254, 96, 91, 165, 78, 27, 119, 177, 34, 2, 9, 60, 254, 65 },
                            MetadataId = new Guid("3e177c71-f84e-4c23-9bf4-b322b350c8b3"),
                            Name = "Amy",
                            Password = "$1$LorS0KcF$e4Un9rhZefzU33Gpsv4aq0",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 233, 47, 31, 234, 230, 193, 216, 120, 106, 210, 59, 1, 185, 97, 163, 245, 209, 135, 144, 179, 43, 129, 21, 214, 17, 50, 14, 210, 95, 128, 122, 229, 252, 36, 218, 133, 233, 253, 43, 94, 159, 182, 251, 147, 66, 40, 42, 91, 126, 246, 186, 190, 255, 201, 166, 106, 241, 80, 197, 16, 46, 212, 251, 44, 212, 26, 135, 204, 159, 218 }
                        });
                });

            modelBuilder.Entity("EFCore.Dal.Models.User", b =>
                {
                    b.HasOne("EFCore.Dal.Models.SysMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId");

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
