// <auto-generated />
using System;
using EFCore.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCore.Dal.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EFCore.Dal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CardNo")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(48)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 162, 34, 79, 13, 50, 151, 76, 218, 98, 210, 68, 1, 248, 24, 200, 34, 68, 245, 79, 231, 136, 38, 40, 126, 200, 91, 117, 89, 58, 250, 69, 55, 221, 100, 200, 169, 99, 118, 41, 32, 80, 160, 158, 122, 146, 167, 145, 14, 40, 223, 209, 27, 192, 231, 185, 205, 164, 98, 18, 5, 97, 133, 129, 12, 163, 74, 146, 218, 195, 146, 143, 0, 226, 58, 185, 45, 227, 43, 40 },
                            Name = "JB",
                            Password = "$1$VsA9ymM.$R18/A5BJ91QQTn6LQuS2.0",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 254, 27, 110, 135, 60, 38, 163, 136, 121, 210, 59, 1, 70, 66, 101, 42, 51, 8, 147, 155, 136, 59, 239, 187, 236, 191, 1, 255, 93, 30, 7, 75, 66, 53, 248, 32, 73, 182, 15, 129, 136, 165, 53, 69, 68, 177, 252, 200, 239, 121, 246, 145, 87, 211, 205, 34, 232, 24, 252, 135, 225, 167, 221, 116, 103, 95, 214, 81, 139, 58 }
                        },
                        new
                        {
                            Id = 2,
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 177, 13, 212, 121, 23, 59, 206, 43, 105, 210, 68, 1, 90, 61, 90, 6, 6, 103, 110, 79, 211, 253, 197, 88, 90, 150, 94, 7, 101, 230, 61, 231, 124, 199, 110, 37, 138, 229, 243, 189, 82, 134, 91, 70, 150, 232, 36, 254, 249, 222, 166, 146, 197, 69, 39, 151, 191, 195, 118, 113, 76, 163, 201, 117, 197, 159, 57, 81, 235, 157, 225, 31, 93, 239, 91, 214, 3, 162, 181 },
                            Name = "Amy",
                            Password = "$1$TMZ2FJHl$Vn/EqMXsMW6SclQoySSXv.",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 148, 84, 52, 180, 128, 68, 42, 225, 110, 210, 59, 1, 237, 240, 108, 57, 230, 239, 97, 116, 13, 176, 18, 136, 205, 178, 191, 34, 28, 29, 154, 165, 178, 126, 28, 181, 212, 70, 85, 30, 190, 40, 223, 201, 222, 89, 32, 32, 118, 88, 118, 70, 123, 211, 74, 180, 3, 254, 214, 79, 124, 239, 49, 46, 191, 238, 3, 164, 94, 215 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
