// <auto-generated />
using System;
using EFCore.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EFCore.Dal.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EFCore.Dal.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("CardNo")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(48)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<byte[]>("Phone")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 211, 253, 90, 14, 96, 111, 116, 140, 121, 210, 68, 1, 93, 230, 121, 32, 89, 220, 94, 77, 14, 52, 211, 232, 228, 212, 38, 89, 233, 79, 57, 64, 123, 144, 173, 97, 83, 129, 129, 103, 167, 139, 163, 66, 210, 254, 169, 182, 184, 174, 216, 113, 103, 0, 151, 182, 152, 161, 124, 246, 199, 109, 44, 129, 13, 124, 105, 114, 238, 12, 10, 218, 71, 103, 148, 6, 66, 49, 170 },
                            Name = "JB",
                            Password = "$1$2wlHwlcj$DHxSHOBtaz/ddzoALxFVS1",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 196, 184, 66, 113, 54, 92, 233, 32, 124, 210, 59, 1, 199, 121, 88, 210, 57, 59, 102, 79, 73, 172, 120, 23, 100, 50, 232, 1, 182, 140, 80, 78, 21, 71, 111, 19, 216, 111, 152, 126, 144, 183, 253, 25, 198, 158, 9, 128, 72, 194, 216, 7, 118, 77, 85, 104, 243, 26, 104, 108, 62, 197, 55, 72, 2, 103, 13, 189, 250, 56 }
                        },
                        new
                        {
                            Id = 2,
                            CardNo = new byte[] { 195, 13, 4, 7, 3, 2, 205, 51, 28, 149, 23, 37, 124, 17, 108, 210, 68, 1, 190, 171, 168, 39, 98, 215, 245, 52, 142, 243, 207, 157, 107, 37, 253, 195, 102, 19, 155, 98, 35, 243, 202, 110, 222, 88, 214, 203, 241, 209, 143, 123, 7, 105, 59, 142, 99, 37, 40, 233, 46, 135, 201, 139, 137, 35, 101, 81, 237, 82, 183, 223, 111, 3, 196, 213, 60, 108, 248, 51, 85, 62, 222, 225, 11, 128, 233 },
                            Name = "Amy",
                            Password = "$1$Gt8pz17h$Za/xAkS.SmNWV03saNR/S.",
                            Phone = new byte[] { 195, 13, 4, 7, 3, 2, 195, 50, 212, 167, 41, 83, 74, 71, 112, 210, 59, 1, 112, 112, 212, 176, 110, 188, 146, 186, 13, 64, 187, 91, 124, 78, 172, 79, 253, 98, 243, 194, 193, 122, 36, 7, 156, 219, 247, 72, 37, 173, 112, 86, 124, 22, 4, 93, 109, 72, 86, 23, 178, 113, 39, 70, 91, 170, 174, 253, 137, 146, 18, 75, 203, 137, 142, 90, 237, 50 }
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
